version: "2.1"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:

      build: .
      command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

      volumes:
        - .:/code/
        - ~/static:/static/
      ports:
        - "80:80"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - SMS_EMAIL=${SMS_EMAIL}
        - SMS_PASSWORD=${SMS_PASSWORD}
        - SMS_SENDER=${SMS_SENDER}
        - ALGORITHM=${ALGORITHM}
        - SECRET_KEY=${SECRET_KEY}
        - LOG_LEVEL=debug
      depends_on:
        - db
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "5050:80"
      depends_on:
        - db
