"""9

Revision ID: 131c6102e999
Revises: f7a6f3c1b86c
Create Date: 2022-08-05 10:31:55.791939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131c6102e999'
down_revision = 'f7a6f3c1b86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('imagepath', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'imagepath')
    # ### end Alembic commands ###
