"""8

Revision ID: 3fb04e4ced35
Revises: 7eadc50ec158
Create Date: 2022-08-05 07:55:28.502318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb04e4ced35'
down_revision = '7eadc50ec158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_category_association_product_id_fkey', 'product_category_association', type_='foreignkey')
    op.create_foreign_key(None, 'product_category_association', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category_association', type_='foreignkey')
    op.create_foreign_key('product_category_association_product_id_fkey', 'product_category_association', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
