"""7

Revision ID: 457adc3979c8
Revises: aa6605794807
Create Date: 2022-08-02 09:25:46.358447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457adc3979c8'
down_revision = 'aa6605794807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
