"""7

Revision ID: 4f08426dd47c
Revises: dc1e919bc767
Create Date: 2022-08-03 13:10:22.768660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f08426dd47c'
down_revision = 'dc1e919bc767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('DELIVERY', 'PICKUP', name='ordertype'), nullable=True),
    sa.Column('status', sa.Enum('PAYMENT', 'PAID', 'DONE', name='orderstatus'), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('bakery_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), nullable=True),
    sa.Column('payment_link', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('cart', sa.JSON(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('products_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['delivery_address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.drop_index('ix_pickup_order_id', table_name='pickup_order')
    op.drop_table('pickup_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_order',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('products_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['delivery_address.id'], name='pickup_order_delivery_address_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='pickup_order_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pickup_order_pkey')
    )
    op.create_index('ix_pickup_order_id', 'pickup_order', ['id'], unique=False)
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
