"""7

Revision ID: 5357938ca505
Revises: a5ded0d19557
Create Date: 2022-08-02 09:33:19.179487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5357938ca505'
down_revision = 'a5ded0d19557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
