"""7

Revision ID: 688c39803fba
Revises: ba0d3905827e
Create Date: 2022-08-04 08:06:37.404750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '688c39803fba'
down_revision = 'ba0d3905827e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('images_paths', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('product', sa.Column('nutritional_value', sa.String(), nullable=True))
    op.drop_column('product', 'nutritional_value_json')
    op.drop_column('product', 'images_paths_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('images_paths_json', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('nutritional_value_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'nutritional_value')
    op.drop_column('product', 'images_paths')
    # ### end Alembic commands ###
