"""7

Revision ID: 6fde8f23bfc8
Revises: 3d585523aa44
Create Date: 2022-08-02 21:01:12.963498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fde8f23bfc8'
down_revision = '3d585523aa44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('promocode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'promocode', ['promocode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'promocode_id')
    # ### end Alembic commands ###
