"""First migration

Revision ID: 7678c39e8b3e
Revises: 
Create Date: 2022-07-25 11:14:50.286851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7678c39e8b3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('attention_text', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('iconpath', sa.String(), nullable=True),
    sa.Column('imagepath', sa.String(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_table('phone_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_code_id'), 'phone_code', ['id'], unique=False)
    op.create_index(op.f('ix_phone_code_phone'), 'phone_code', ['phone'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('ADMIN', 'USER', 'DELETED', name='accounttype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('bonus_card2',
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_card2_id'), 'bonus_card2', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonus_card2_id'), table_name='bonus_card2')
    op.drop_table('bonus_card2')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_phone_code_phone'), table_name='phone_code')
    op.drop_index(op.f('ix_phone_code_id'), table_name='phone_code')
    op.drop_table('phone_code')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_table('campaign')
    # ### end Alembic commands ###
