"""First migration

Revision ID: 772a2a1ad91d
Revises: 822ed3b32496
Create Date: 2022-07-26 19:26:14.658300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772a2a1ad91d'
down_revision = '822ed3b32496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
