"""7

Revision ID: 7eadc50ec158
Revises: 9186231f0c3d
Create Date: 2022-08-04 10:20:10.828799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eadc50ec158'
down_revision = '9186231f0c3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('composition', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'composition')
    # ### end Alembic commands ###
