"""First migration

Revision ID: 822ed3b32496
Revises: 7678c39e8b3e
Create Date: 2022-07-26 18:57:46.953342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822ed3b32496'
down_revision = '7678c39e8b3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
