"""7

Revision ID: 987accaf0c2e
Revises: 6fde8f23bfc8
Create Date: 2022-08-03 06:46:10.539659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987accaf0c2e'
down_revision = '6fde8f23bfc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
