"""7

Revision ID: a5ded0d19557
Revises: 9cf4b0a64b10
Create Date: 2022-08-02 09:30:39.036098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ded0d19557'
down_revision = '9cf4b0a64b10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cart', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cart')
    # ### end Alembic commands ###
