"""7

Revision ID: bb80b6a09bae
Revises: 987accaf0c2e
Create Date: 2022-08-03 06:48:06.298750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb80b6a09bae'
down_revision = '987accaf0c2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
