"""7

Revision ID: dc1e919bc767
Revises: 3ac282d40b6e
Create Date: 2022-08-03 07:01:04.228689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1e919bc767'
down_revision = '3ac282d40b6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'total')
    # ### end Alembic commands ###
