"""5

Revision ID: defdcfb92207
Revises: 7beaa1ac43a9
Create Date: 2022-08-02 08:25:48.840205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defdcfb92207'
down_revision = '7beaa1ac43a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cart', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cart')
    # ### end Alembic commands ###
