"""9

Revision ID: f7a6f3c1b86c
Revises: 4aef18fd3381
Create Date: 2022-08-05 09:15:01.422526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a6f3c1b86c'
down_revision = '4aef18fd3381'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('user', 'patronymic')
    op.drop_column('user', 'family')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('family', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
